isolating open source

diff --git a/.github/workflows/appsec.yml b/.github/workflows/appsec.yml
--- a/.github/workflows/appsec.yml
+++ b/.github/workflows/appsec.yml
@@ -44,15 +44,15 @@ jobs:
 
       - name: Snyk Open Source # For testing and failing please add snyk test before snyk monitor
         run: |
-          snyk test --all-projects --sarif >opensource.sarif || true
+          snyk test --all-projects --sarif > opensource.sarif || true
      #     snyk monitor --all-projects --project-business-criticality=critical --project-tags="component=pkg:juice-shop-bash@main" --org=8732cc6d-085e-4f1d-ba98-cf4b491723fb || true     
      # - name: Snyk Code HTML # Remove || true to fail if there are vulnerabilities
      #   run: |  
      #      snyk code test --json | snyk-to-html -o results-code.html || true
 
-      - name: Snyk Code SARIF # Remove || true to fail if there are vulnerabilities
-        run: |  
-           snyk code test --sarif  > results.sarif || true
+     # - name: Snyk Code SARIF # Remove || true to fail if there are vulnerabilities
+     #   run: |  
+     #      snyk code test --sarif  > results.sarif || true
 
      # - name: Change Severity
       #  run: python example.py --file results.sarif | jq > results.sarif
@@ -80,10 +80,10 @@ jobs:
       #    name: results-code
       #    path: results-code.html
             
-      - name: Upload Code SARIF file
-        uses: github/codeql-action/upload-sarif@v3
-        with:
-          sarif_file: results.sarif
+      #- name: Upload Code SARIF file
+      #  uses: github/codeql-action/upload-sarif@v3
+      #  with:
+      #    sarif_file: results.sarif
       - name: Upload Open Source SARIF file
         uses: github/codeql-action/upload-sarif@v3
         with:
