debugging sarif upload

diff --git a/.github/workflows/appsec.yml b/.github/workflows/appsec.yml
--- a/.github/workflows/appsec.yml
+++ b/.github/workflows/appsec.yml
@@ -46,6 +46,15 @@ jobs:
       - name: Snyk Code SARIF # Remove || true to fail if there are vulnerabilities
         run: |  
            snyk code test --sarif  > results.sarif || true
+
+      - name: Set SARIF file permissions
+        run: chmod 644 results.sarif
+        
+      - name: Check SARIF file size
+        run: |
+          if [ ! -s results.sarif ]; then
+          echo "SARIF file is empty or invalid"; exit 1
+          fi
       
       #- name: Snyk IaC # Remove || true to fail if there are vulnerabilities
       #  run: |
